# Generated by Django 4.1.1 on 2022-10-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['unit']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('lbs', 'Pound'), ('tbsp', 'Ounce'), ('grams', 'grams'), ('kilo', 'kg'), ('Egg', 'egg')], default='lbs', max_length=15),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
